[project]
name = "angewandte-programmierung-projekt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "pytest>=9.0.3",
    "requests>=2.33.1",
    "sqlmodel>=0.0.22",
    "faker>=37.0.0",
    "streamlit>=1.57.0",
]
